#set math.equation(numbering: "(1)")
#[
  #set page(numbering: {})
  #set align(center)
  #show heading: set block(above: 8 * 1.65em, below: 1.65em)
  // #show heading(level: 1): set text(2em)
  // #show heading(level: 2): set text(weight: "regular", style: "italic")

  = Magnetic Field of a Solenoid
  == Hayden Pott

  Lab Date: 3 April 2025 \
  Lab Section: 004 \
  Lab Parter: Erik Claros \
]

#let proc_err(expected, actual) = [#{
  let n = calc.abs((expected - actual) / expected) * 100;
  calc.round(n, digits: 2)
}%];

#let ohm = [Ω];
#let uF = [µF];

== Objective

The objective of this lab is to study the magnetic fields created by a solenoid
by mapping the field and measuring the magnetic field within a solenoid.

== Theory

When a coil of wire has an electric charge run through it, it generates a
magnetic field.  This charged coil is called a solenoid.  The strength of the
field in the middle of a solenoid can be measured by $
B = N/L mu_0 i
$ where $N$ is the number of turns, $L$ is the length of the coil and $mu_0 = 4
pi 10^(-7)$.

== Procedure

=== Procedure A

Setup a solenoid connected to the power supply.  Using a small compass, trace
the north/south pole to draw the lines of the magnetic field.

=== Procedure B

Attach a slinky to the table, stretched to a length of one metre.  Insert the
magnetic probe and attach the power supply to each end of the slinky.  After
recording data for a few seconds, turn on the power supply, wait a few seconds,
then turn it back off.

=== Procedure C

Using the same setup from Procedure B, set the current to 0.2 A.  Storing the
runs between, measure the magnetic field 5 times, recording the average and
standard deviation each time.

== Data

=== Procedure A

#image("./proc-a.png")

=== Procedure B

The length of the slinky was 1.005 m, with 80 turns. \
The average collected from the Logger Pro software was 0.000055 T

#image("./proc-b.png")

=== Procedure C

The length of the slinky was 1.005 m, with 80 turns. 

#table(
  columns: (auto, auto, auto, auto),
  [Run], [I (A)], [Average B-Field(mT)], [$sigma$ (mT)],
  [1], [0.2], [0.0170], [0.0009],
  [2], [0.4], [0.0387], [0.0016],
  [3], [0.6], [0.0592], [0.0014],
  [4], [0.8], [0.0805], [0.0014],
  [5], [1], [0.1005], [0.0014],
)

#image("./proc-c.png")

== Analysis

=== Procedure B

The average value collected in Logger Pro was 0.000055 T.  Using the formula
discussed in the theory section, we can calcualte the theoretical $mu_0$ at
0.000050 T.  This gives us an error of #proc_err(.00005, .000055)

=== Procedure C

Using the data collected from proc c, we can plot the $N/L i$ vs the average B
field, giving us the following graph:

#image("./proc-c-anal.png")

Getting the slope and standard deviation of the slope using the provided table,
we get that the $mu_0 = 0.0000013 plus.minus 0.00098$

The theoretical $mu_0$ is $0.000001257$, giving us a #proc_err(0.000001257,
.0000013) error.

== Conclusion

In conclusion, we were able to visualse and measure the effects of a magnetic
field generated by a solenoid.

As with any experiment, there are errors.  The power supply, in this case, is
very prone to error as its values constantly change.  There is a chance that we
bumped it between setting it to a value and mesuring the result.

